### PR TITLE
Merge into master

### PR DESCRIPTION
**Pull request by fireice-uk**
@psychocrypt do you want to do anything else? I think we are ready to call this one.

### CODE REVIEW

**Comment by psychocrypt** [comment]
I will run some tests today to verify the changes. Do you checkt the auto adjust for systems without L3?

**Comment by fireice-uk** [comment]
I would much rather do a basic version that handles 80-90% cases and then polish it.

**Comment by psychocrypt** [comment]
Could we add a check that if no L3 is detected that the cfg for one thread is shown. This is maybe far away from the optimum but a working config.

**Comment by fireice-uk** [comment]
Sounds good, will do in a sec.

**Comment by psychocrypt** [comment]
I tested this pull request and the performance without huge memory pages looks good. I can't test the last commit with the fallback to the one thread config.

**From my side ready to merge!**

**Comment by fireice-uk** [comment]
OK! Let's get this show on the road! Be prepared for the tomatoes though lol

**Pull request merged**
