### PR TITLE
Initial Travis CI script added

### PR DESCRIPTION
**Pull request by ruzickap**
Initial Travis CI script added. It should help with #149 
You can see the example here: https://travis-ci.org/ruzickap/xmr-stak-cpu
To make Travis CI working for the project you need to configure + enable the xmr-stak-cpu on their web page.

### CODE REVIEW

**Comment by fireice-uk** [comment]
@psychocrypt Can you ok this? In my line of work CI means hitting the build button every 30 minutes =)

**Comment by psychocrypt** [comment]
@ruzickap Thanks for this script this was long time on my TODO list.
@fireice-uk You need to activate the hook for travis in the backend of github.I have not the rights to do it.

**Comment by ruzickap** [comment]
I'll improve it, once @fireice-uk will activate the travis ci and merge it. I'll need to work on osx support, but this is just a first "draft" working with "default ubuntu" only....

**Comment by fireice-uk** [comment]
Registered and merged, looks like it is working :+1:

**Pull request merged**
