### PR TITLE
AWS + Azure benchmarks added

### PR DESCRIPTION
**Pull request by ruzickap**
Adding scripts which may help to benchmark xmr-stak-cpu using AWS instances. Maybe this can be handy for somebody...

### CODE REVIEW

**Comment by psychocrypt** [comment]
@ruzickap That is a fantastic work but I am not sure if we should move this scripts to the reposetory.

@fireice-uk Could you please decide if we should add this to the repository. Maybe this should be a independent repository under @ruzickap  account. The reason for this is that nobody of us will administrate this benchmarks and the scripts and results will be soon outdated and we will spend a lot of or working time to fix and test the scripts.

**Comment by fireice-uk** [comment]
@psychocrypt I like the addition in principle. Can you do a more thorough review? I'm fairly busy this week.

**Comment by ruzickap** [comment]
Hello gents.
I do not expect to update the results of the benchmarks in the future. These "scripts" may be handy for somebody who wants to do it's own benchmarks - for example between AWS/Azure/GCP or private cloud based on Vmware/Openstack.
I wrote it for myself and just want share it with other people, because it may save time for somebody who would like to compare the miners or CPUs / VMs...

**Comment by fireice-uk** [comment]
@ruzickap  @psychocrypt I had a chat with few people running AWS, and they all said this is likely to require maintenance, which I cannot provide as I'm not planning on deploying AWS. If that assertion is correct I would reject it in the miner proper (better to have no code than broken code).

**Comment by psychocrypt** [comment]
@fireice-uk Yes that's exactly my opinion, but I would be happy if @ruzickap  can create a small project within his github account to keep the current state and give other community members the opportunity to fork the project or create pull requests.

@ruzickap Can you create a own repository with a short readme.

**Comment by charleswg** [comment]
Just happened to google to this and I think this could be relevant. 

I tested out C4 compute instance (c4.xlarge, supposedly no throttling) and found that the same hardware (based on lscpu) Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz 4 cores does not perform the same using xmr-stak-cpu using the same config and clone instances. In fact it varies so much (110-320 H/s) that it's probably not worthwhile to benchmark in AWS environment.  Something is very fishy there.

**Pull request closed without merging**
