### PR TITLE
Hard guard on console events to prevent excessive CPU use

### PR DESCRIPTION
**Pull request by fireice-uk**
@psychocrypt This should fix any possibility of event spam occurring in get_key() - can you verify it? Also what would be the best way of pushing it to master so users can roll out the fix?

### CODE REVIEW

**Comment by psychocrypt** [comment]
I opened a pull request to this pull. The current version not keep the time between two rounds.
@fireice-uk  If this was not the intention of this pull request please close my PR.

**Comment by psychocrypt** [comment]
> Also what would be the best way of pushing it to master so users can roll out the fix?

## there are two ways

first way:
- prepare everything in the dev branch (README.txt and version.hpp)
- open a pull request from dev to master

second way (better way):

- create a new release candidate branch out of the dev branch 
  - this allow to add new features to dev during you have time to prepare the windows binaries and update the hashes
  - there is no need to finish the release candidate within a few hours
  - if we found bugs, we have time to backport the bugs to the rc branch
- change README.txt (hash for the new binaries) and version.txt
- test again the rc branch
- open a PR from rc to master
- release the master
- Note: now master is ahead of dev
- merge master back to dev

**Comment by psychocrypt** [comment]
The goal of this PR is to solve #116

**Comment by psychocrypt** [comment]
@fireice-uk  observation: If I start the miner with `./xmr-stak-cpu &` the miner moves to the background and stops working. Only if I bring it back to the foreground it begin to work. 
I don't know way but the threads were not started before the miner goes to the foreground.

**Comment by psychocrypt** [comment]
The function call `tcsetattr( STDIN_FILENO, TCSANOW, &newattr );` is blocking the hole process as soon as the process is started in the background.

**Comment by psychocrypt** [comment]
A process which is in the background and tries to read from `stdin` is going to sleep. [see this stackoverflow post](https://stackoverflow.com/a/16053095)

**Comment by fireice-uk** [comment]
Ty for doing the research on this one =)

**Comment by psychocrypt** [comment]
@fireice_uk we should add a paramter in the config to enable deamon mode. If deamon mode is enable the thread which is reading from stdin is not spawned.
This schould solve the issue.

**Comment by fireice-uk** [comment]
Yes, will do that this evening +1:

**Comment by fireice-uk** [comment]
Closing as this topic evolved to daemon mode

**Pull request closed without merging**
