### PR TITLE
merge master back to dev

### PR DESCRIPTION
**Pull request by psychocrypt**
This PR also update the version number with the postfix `dev`

### CODE REVIEW

**Comment by psychocrypt** [comment]
@fireice-uk You you please enable in the back end that it is not allowed to merge a pull request if the CI is not finished and all tests passed.

**Comment by psychocrypt** [comment]
Something is wrong with the windows CI build . The error is equal to #235

```
"C:\xmr-stak-cpu\xmr-stak-cpu.sln" (default target) (1) ->
"C:\xmr-stak-cpu\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj.metaproj" (default target) (6) ->
"C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj" (default target) (7) ->
(Link target) -> 
  LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
"C:\xmr-stak-cpu\xmr-stak-cpu.sln" (default target) (1) ->
"C:\xmr-stak-cpu\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj.metaproj" (default target) (6) ->
"C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj" (default target) (7) ->
(Link target) -> 
  cli-miner.obj : error LNK2001: unresolved external symbol OpenSSL_add_all_digests [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
  cli-miner.obj : error LNK2001: unresolved external symbol SSL_load_error_strings [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
  cli-miner.obj : error LNK2001: unresolved external symbol SSL_library_init [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
  cli-miner.obj : error LNK2001: unresolved external symbol ERR_load_crypto_strings [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
  socket.obj : error LNK2001: unresolved external symbol SSLv23_method [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
  C:\xmr-stak-cpu\bin\Release\xmr-stak-cpu.exe : fatal error LNK1120: 5 unresolved externals [C:\xmr-stak-cpu\xmr-stak-cpu.vcxproj]
    31 Warning(s)
    6 Error(s)
Time Elapsed 00:00:20.65
```

**Comment by fireice-uk** [comment]
> You you please enable in the back end that it is not allowed to merge a pull request if the CI is not finished and all tests passed.

I really don't like when a "computer says no" - any rationale for enabling it? I can see that being a problem for a large team but here it is just us - surely we both know when something is a merge-preventing issue (like #220) and when it something is not.

Just in case you need more evidence for this being an external issue, the commit that first showed this symptom is 6ae5e35 which didn't touch the source code (in fact it didn't change at all since the last successful build)

**Comment by fireice-uk** [comment]
Let me know if you think this pr is ok to merge.

**Comment by psychocrypt** [comment]
> I really don't like when a "computer says no" - any rationale for enabling it?

The reason for this is that we now have a release where we know that something is wrong with the windows build. We need now to fix the issue because user got the same error than the CI is showing. After we applied a fix the release is broken (the windows build) up to the next release, this can be avoided if only PR those passed the CI can be merged.

**Comment by psychocrypt** [comment]
I will rebase this PR after #238 is merged, this give us time to merge all other PRs while I am searchin for the reason (maybe a now OpenSSL binary/ or we compile it by hand)

**Comment by fireice-uk** [comment]
Yes, I made that call because I know that the issue is external to the code in the repo. The root problem is relying on code downloaded from a 3rd party. 

Look at it this way - if next time one of the links 404s then we need to stop all work until we find a replacement.

**Comment by psychocrypt** [comment]
> Look at it this way - if next time one of the links 404s then we need to stop all work until we find a replacement.

Yes, but we can disable it very fast^^. 
I will try if we can compile the dependencies, I hope that is not to hard.

**Comment by fireice-uk** [comment]
@psychocrypt It isn't. As I said in the issue, libc incompatibility errors are the reason why I usually compile the whole dependency stack from source on Windows.

**Comment by psychocrypt** [comment]
@fireice-uk Could you please merge this to avoid conflicts with #240

**Pull request merged**
