### PR TITLE
Compiles on macOS

### PR DESCRIPTION
**Pull request by bhayer**
No need to install GCC, works fine with CLANG Compiler

### CODE REVIEW

**Comment by fireice-uk** [comment]
Can you confirm that CPU affinity works and put some logs of a run with and without large pages? Those were two main issues with macos

**Comment by bhayer** [comment]
On my machine i have ~120 H/s without large pages (same value with wolfs cpuminer), with large pages enabled it reaches ~190 H/s

**Comment by fireice-uk** [comment]
How about cpu affinity?

**Comment by fireice-uk** [comment]
Also, can you please rebase?

**Comment by bhayer** [comment]
I'm afraid I can't confirm that cpu affinity is working. Don't understand why right now, because it should...

**Comment by fireice-uk** [comment]
Ok. At least we have one feature working then :). Can you perhaps have a look if it can either be made to work, or disable the option via a config error in jconf.cpp ? I don't want to have options that have no effect.

**Comment by stroborobo** [comment]
Doesn't build here unfortunately, looks like `_rotr` is missing on macOS.

```
[  6%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_blake256.c.o
clang: warning: argument unused during compilation: '-s'
[ 13%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_groestl.c.o
clang: warning: argument unused during compilation: '-s'
[ 20%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_jh.c.o
clang: warning: argument unused during compilation: '-s'
[ 26%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_keccak.c.o
clang: warning: argument unused during compilation: '-s'
[ 33%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_skein.c.o
clang: warning: argument unused during compilation: '-s'
[ 40%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/soft_aes.c.o
clang: warning: argument unused during compilation: '-s'
/Users/bo/src/xmr-stak-cpu/crypto/soft_aes.c:196:23: warning: implicit declaration of function '_rotr' is invalid in C99 [-Wimplicit-function-declaration]
        return _mm_set_epi32(_rotr(X3, 8) ^ rcon, X3,_rotr(X1, 8) ^ rcon, X1);
                             ^
1 warning generated.
[ 46%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/crypto/cryptonight_common.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 53%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/cli-miner.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 60%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/console.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 66%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/executor.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 73%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 80%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/jconf.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 86%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/jpsock.cpp.o
clang: warning: argument unused during compilation: '-s'
[ 93%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/minethd.cpp.o
clang: warning: argument unused during compilation: '-s'
[100%] Linking CXX executable bin/xmr-stak-cpu
ld: warning: option -s is obsolete and being ignored
Undefined symbols for architecture x86_64:
  "__rotr", referenced from:
      _soft_aeskeygenassist in soft_aes.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/xmr-stak-cpu] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2
```

Maybe add a define as a replacement on non-windows platforms like this?

```
#define _rotr(v, c) (((v) >> (c)) | ((v) << (sizeof(v) * 8 - (c))))
```

**Comment by bhayer** [comment]
_rotr is an Intel intrinsic that GCC knows about, but is not defined for Clang
Yes, you can use a define or just check out version 1.1.0.

As far as i can say, it should not affect performance, please correct me if I'm wrong.

You should be able to get ~50-60 H/s per 2MB L3 Cache on a i5 CPU

**Comment by fireice-uk** [comment]
It will - ROTR is a single asm instruction, the method above maps to 3 instructions if I remember correctly.

**Comment by fireice-uk** [comment]
MacOS support now has been integrated into the main branch. Thanks for you help.

**Pull request closed without merging**
