### PR TITLE
release condidate 1.5.0

### PR DESCRIPTION
**Pull request by psychocrypt**
This is the release candidate for the next release of `xmr-stak-cpu`.

@fireice-uk I added here a small todo list, please feel free to extend the list if I missed something. Version number changes can be done directly on top of this PR and if bugfixes are nedded we do it on the dev and cherry pick the commits to this branch. **attention** This PR is located in your repository.

# Todo
- [x] update version number to [this](https://github.com/fireice-uk/xmr-stak-amd/blob/master/version.h#L4) style
- [x] create windows binaries
- [x] update windows binary sha256 hashes
- [x] cherry-pick #227 
- [x] windows runtime tests
- [x] linux runtime tests

### CODE REVIEW

**Comment by fireice-uk** [comment]
@psychocrypt I approved #227 can you cherry-pick it to this pr?

**Comment by psychocrypt** [comment]
@fireice-uk  I cherry-picked #227I will now to some linux tests.

**Comment by psychocrypt** [comment]
Linux tests done: with clang 3.8 and gcc (note: the binary compiled with clang is slightly faster)

**Comment by psychocrypt** [comment]
Windows tests done: tested also the api.json feature under windows

**Pull request merged**
