### PR TITLE
add Windows VS2017 support

### PR DESCRIPTION
**Pull request by psychocrypt**
- add windows socket libraries
- search for windows name of all dependencies
- add missing link step to the intermediate static library

### CODE REVIEW

**Comment by fireice-uk** [comment]
Is the command line to test it `cmake -G "Visual Studio 14 Win64"`?

**Comment by psychocrypt** [comment]
Yes with this command you could test it. Please follow all instructions from #161 because the VS build environment must be loaded before cmake is called.
Cmake is than creating a VSproject which can be compiled with VC or via msbuild

**Comment by GTANAdam** [comment]
I have found this extremely useful, well done!
While following the how-to, I have ran into a couple of issues that I have fixed in the following commit 1a1d7b4697ed8c72350fdff582f87e101a565599, feel free to import the changes.

**Comment by psychocrypt** [comment]
@GTANAdam Thx for testing, I will add parts of your docmentation fixes to the pull request.

**Comment by fireice-uk** [comment]
Looks good for VS14 too. There is one semi-cosmetic problem - `cl : Command line warning D9002: ignoring unknown option '-msse2'` `cl : Command line warning D9002: ignoring unknown option '-maes'` - GCC options are passed to MSVC, can we avoid that?

**Comment by psychocrypt** [comment]
I can add a guard that the options are not passed for msvs. 
It is "only" a warning therefor it would be nice to merge the current state and I will provide a fix for the warning soon.

**Comment by fireice-uk** [comment]
@psychocrypt Yes, I beat you to that one =)

**Pull request merged**
