### PR TITLE
optimize double hash implementation

### PR DESCRIPTION
**Pull request by psychocrypt**
use single hash implementation within the function `cryptonight_double_hash`

The way how the single hash implementation is implemented is more efficient than the implementation from the double hash function. With the new implementation I get a small performance increase.

2 x Xeon(R) CPU E5-2630 v3 @ 2.40GHz - 4 threads double hash (low power mode) and 12 threads used single hash 
old: 905 H/s
PR: 929 H/s
= 2,6% improvement

i7-4600U CPU @ 2.10GHz compare 1 thread with double hash (low power mode)
old: 105 H/s
PR: 115 H/s 
= 9,5% improvement

The i7 run was only a test to compare the old low_power_mode with the new implementation, for the i7 two threads without low power mode are still faster (121 H/s)

## Test

- [x] mine against a pool and let the pool verify the results

### CODE REVIEW

**Comment by fireice-uk** [comment]
@psychocrypt Looks good but I will have a look at register utilisation in ASM. I'm not quite sure if the compiler can fit all that into general registers (16 on x64) - and if that's the case it would need more testing (as L1 speed comes into play).

**Comment by psychocrypt** [comment]
@fireice-uk I will test it also on AMD and some other Intel systems.

**Comment by michael-sewell** [comment]
In case it's useful feedback, I tested this change on an EC2 c4.large and observed a 150->160 h/s improvement.

**Comment by psychocrypt** [comment]
one hash vs. two hashes(dev) vs. two hashes(PR) 

| CPU | low_power_mode | dev H/s | PR H/s | increase
|------|-------|-----|-----|---|
| Xeon(R) CPU E5-2630 v3 @ 2.40GHz | false | 56.4 | 56.4 | 0%
| Xeon(R) CPU E5-2630 v3 @ 2.40GHz | true | 93.7 | 100.5 | 7.3%
| Xeon(R) CPU E5-2609 0 @ 2.40GHz | false | 44.8 | 44.8 | 0%
| Xeon(R) CPU E5-2609 0 @ 2.40GHz | true | 74.6 | 78.5 | 5.2%
|Xeon(R) CPU E5-2603 v3 @ 1.60GHz (noAES) | false | 13.0 | 13.0 | 0%
| Xeon(R) CPU E5-2603 v3 @ 1.60GHz (noAES) | true | 15.1 | 15.3 | 1.3%
| AMD Opteron(TM) Processor 6276 | false | 58 | 58.9 | 0%
| AMD Opteron(TM) Processor 6276 | true | 56.3 | 66.4 | 17.9%

**Comment by karl-rovelution** [comment]
Am I correct, looking at your benchmarks, in understanding that there's a significant performance increase (nearly 2x!) switching to low_power_mode=true for certain CPU architectures? This would really be useful to have in the config docs -- I had been under the assumption that low_power_mode=false would always provide maximum performance.

**Comment by LutherDiaz** [comment]
xeon E5-1630 v4 
dev 272.7 H/s
pr 241.5 H/s

anything I've missed in the configuration?

**Comment by psychocrypt** [comment]
@karl-rovelution I used for the benchmarks only one core to compare the changes if low power mode is activated. Using one thread per hash will give you better results but some systems has so much cache that you need the liw powet mode to utilize the cache to get the max out of your system. In such a case this PR is very usefull.

@LutherDiaz What do you benchmarked? One thread, the full system. Please post your config.

**Comment by fireice-uk** [comment]
@psychocrypt 
I verified that the code does not hit the stack in the inner loop. Here is a pastebin of the ASM code generated by MSVC if you want to admire it =) https://pastebin.com/zHMJMgVV

**Comment by fireice-uk** [comment]
@karl-rovelution The place the low_power_mode shines are VMs where you only have one core but (potentially) a lot of cache. In such cases the performance is indeed 200%, otherwise you are still limited by the cache.

**Comment by psychocrypt** [comment]
@fireice-uk I think we can metge it and after @LutherDiaz respons we can evaluate his results.

**Comment by psychocrypt** [comment]
@karl-rovelution  low power_mode can also be usefull if you are mining with many gpus and the cpu on the same system, depending of the system design it could help to have a free core to handle the gpu transfers. It could help to use one low_power threads instead of two tgreads using each one hash.

**Comment by karl-rovelution** [comment]
@psychocrypt Yeah, the obvious solution to determine the best configuration for a particular setup I'm finding is "benchmark, benchmark, and benchmark more." I've been using cloud-based servers (typically using Xeon Haswell v3s)  and have found that the best performance so far appears to be off of 1-2 core systems, low power mode on, one thread/core. IE, 8x 2-core systems with that low-power configuration performs much better than 1x 16-core system (either low or high power mode).

Is there a wiki or somewhere which we could post different configurations / specs / hashrates?

**Pull request merged**
