### PR TITLE
Initial JSON API implementation

### PR DESCRIPTION
**Pull request by fireice-uk**
Needs some testing.

### CODE REVIEW

**Comment by psychocrypt** [comment]
Could you give add description, I don't know which feature this PR adds and what must be tested.

**Comment by psychocrypt** [comment]
@fireice-uk Is this PR the monitoring API from issue #163?

**Comment by fireice-uk** [comment]
@psychocrypt Correct. The url is going to be /api.json Error conditions need most testing.

**Comment by psychocrypt** [comment]
@fireice-uk I don't get it, I started the miner and try to connect to `127.0.0.1/api.json` but there is nothing. Please add add some documentation how this PR can be tested.

**Comment by fireice-uk** [comment]
Unless you set the httpd port in the config ("httpd_port") to 80 (requires root) then "http://127.0.0.1/api.json" is not going to work, navigate to "http://127.0.0.1:<port_no>/api.json"

**Comment by fireice-uk** [comment]
What needs most testing are the error reports (both the result error tally, and the connection error log)

**Comment by psychocrypt** [comment]
@fireice-uk I tested the json api as good as I can with connection errors. 
There is one question, is the error log showing all errors since the start or only the last N?
If all errors are shown than it could be that the json blob get very big and expensive to download.

**Comment by fireice-uk** [comment]
They way stak works is that it is a log, if it becomes a problem then we can put a limit of say 100 entries there.

**Comment by psychocrypt** [comment]
Thx for the clarification. IMO we can merge it.

**Comment by psychocrypt** [comment]
One point more: can you please add a short section to the file README.md, can also be a new PR.

**Comment by fireice-uk** [comment]
I will do it on this PR. Squashed two bugs first =). The double counting was present since alpha actually, nobody noticed since it doesn't apply to the first error.

**Comment by fireice-uk** [comment]
This should be everything on this topic =). Merging.

**Pull request merged**
