### PR TITLE
CPU autoconfig

### PR DESCRIPTION
**Pull request by fireice-uk**
Needs AMD test - I wrote that part 100% dry, using only the AMD manual.

### CODE REVIEW

**Comment by psychocrypt** [comment]
I tested it on a 4 socket system, I will print only the design of the first socket because you wrote the auto suggestion is currently not designed for server.

## AMD Opteron 6276

One socket contains 16 cores. 8 cores are on one die and two dies are combined under a heat plate. 

```
Machine#0(252GB)
  Socket#0(63GB)
    NUMANode#0(31GB)
      L3(6144KB)
        L2(2048KB)
          L1d(16KB)
            Core#0
              PU#0
          L1d(16KB)
            Core#1
              PU#1
        L2(2048KB)
          L1d(16KB)
            Core#2
              PU#2
          L1d(16KB)
            Core#3
              PU#3
        L2(2048KB)
          L1d(16KB)
            Core#4
              PU#4
          L1d(16KB)
            Core#5
              PU#5
        L2(2048KB)
          L1d(16KB)
            Core#6
              PU#6
          L1d(16KB)
            Core#7
              PU#7
    NUMANode#1(31GB)
      L3(6144KB)
        L2(2048KB)
          L1d(16KB)
            Core#0
              PU#8
          L1d(16KB)
            Core#1
              PU#9
        L2(2048KB)
          L1d(16KB)
            Core#2
              PU#10
          L1d(16KB)
            Core#3
              PU#11
        L2(2048KB)
          L1d(16KB)
            Core#4
              PU#12
          L1d(16KB)
            Core#5
              PU#13
        L2(2048KB)
          L1d(16KB)
            Core#6
              PU#14
          L1d(16KB)
            Core#7
              PU#15
```

Suggestion:

```
[2017-04-25 21:25:33] : Autoconf L3 size detected at 12288.
[2017-04-25 21:25:33] : Autoconf cores detected at 64 on Linux.

**************** Copy&Paste ****************

"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
]
```
The suggestion is only checking the L3 cache but the L2 cache is 2MiB this means per 2cores one hash can be computed.
There is also a mistake in the number of threads if only the L3 is used 12MiB cache should result in 6 threads not 7.
The suggestion should be

```
"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 12 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 14 },
]
```

**Comment by fireice-uk** [comment]
CPU caches will usually be inclusive meaning L2 is a faster copy of L3, you can't store data there. 7 threads is indeed an off-by-one bug.

Linux will stagger the cores automagically (check `cat /proc/cpuinfo`)

**Comment by psychocrypt** [comment]
For AMD all cores are native cores but from the design 2 native cores share one 2MiB L2 cache, therefore it is useful to set the affinity only to even cores to benefit from the L2 per 2 cores.

**Comment by fireice-uk** [comment]
@psychocrypt That won't apply to the Zen arch, right? They have their own hyperthreading there?

**Comment by psychocrypt** [comment]
Tested a intel system with large 20MiB L3 cache  but only 8 native cores and 8 HT.

suggestion ( the so called of-by-one bug):

```
[2017-04-25 21:45:08] : Autoconf L3 size detected at 20480.
[2017-04-25 21:45:08] : Autoconf cores detected at 32 on Linux.

**************** Copy&Paste ****************

"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
]
```

Ideal:

```
"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
]
[2017-04-25 21:45:08] : Autoconf L3 size detected at 20480.
[2017-04-25 21:45:08] : Autoconf cores detected at 32 on Linux.

**************** Copy&Paste ****************

"cpu_threads_conf" :
[
   { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 0 },
   { "low_power_mode" : true, "no_prefetch" : true, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 }
]
```

Design:

```
Machine#0(252GB)
  NUMANode#0(126GB)
    Socket#0
      L3(20MB)
        L2(256KB)
          L1d(32KB)
            Core#0
              PU#0
              PU#16
        L2(256KB)
          L1d(32KB)
            Core#1
              PU#1
              PU#17
        L2(256KB)
          L1d(32KB)
            Core#2
              PU#2
              PU#18
        L2(256KB)
          L1d(32KB)
            Core#3
              PU#3
              PU#19
        L2(256KB)
          L1d(32KB)
            Core#4
              PU#4
              PU#20
        L2(256KB)
          L1d(32KB)
            Core#5
              PU#5
              PU#21
        L2(256KB)
          L1d(32KB)
            Core#6
              PU#6
              PU#22
        L2(256KB)
          L1d(32KB)
            Core#7
              PU#7
              PU#23
```

**Comment by psychocrypt** [comment]
> @psychocrypt That won't apply to the Zen arch, right? They have their own hyperthreading there?

Yes Zen has there own HT. But I have no Zen arch for testing :-( IMO the Zen HT is handled by the OS in linux like with intel [0;NnativeCores) and [NnativeCores;NnativeCores+NhtCores)

**Comment by fireice-uk** [comment]
Try now. It should correctly select 0 - 9 for 20MB cache Intel now. I will have a look at the AMD manual to see if I can pull out arch / ht setting.

**Comment by psychocrypt** [comment]
I can confirm that 95ba2f9 fixes the of-by-one bug

**Comment by fireice-uk** [comment]
Can you verify that the AMD cpu is correctly detected and staggered per "module"?

**Comment by psychocrypt** [comment]
@fireice-uk I opened a pull request to your pull request to fix a small issue with overwritten local variables and wrong method signatures.

**Comment by kth5** [comment]
## **AMD A10-7860K / 4MB L2 / 0MB L3 / 4 cores.**

I do get the following:

>[2017-04-26 02:02:30] : Autoconf failed: L3 size sanity check failed 0.`

Best config comes with using only core 0 and 2 and gives a good 100H/s:

>"cpu_threads_conf" :
[
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
],

**Comment by psychocrypt** [comment]
The A10 is not containing any L3 instead there is 2x2MiB L2 available.

**Comment by psychocrypt** [comment]
> CPU caches will usually be inclusive meaning L2 is a faster copy of L3, you can't store data there.

Note for future improvements: The AMD Opteron I used has exclusive cache, in that case 8 threads fro the native threads increases the performance over 6 threads. The processor contains 6MiB L3 Cache per 4 Cores and 2MiB L2 per 2 Cores, one Socket contains 16 native cores. 

Fun fact: using 10 instead of 8 threads increase the performance again.

**Pull request merged**
